### ISSUE TITLE
Quirk not working

### ISSUE THREAD

**Issue by Sonusss** [glcos/PTVOquirk#1]
Hi,

I'm trying to duplicate exactly your setup as a base for my own development  but no success.
ptvo.switch is only recognized as basic switch.

![image](https://user-images.githubusercontent.com/51654027/134814706-c9e78be3-48d9-4ec6-8a33-4e11cab3a17d.png)

I placed the ptvo.py file at right place:  /usr/local/lib/python3.9/site-packages/zhaquirks/
deleted pycache
restarted
No error in logs

Can you help ?

**Comment by glcos** [comment]
Custom quirks have to go into a specific folder.
Try to create a folder such as /home/homeassistant/custom_zha_quirks/ptvo and put the file ptvo.py there.
Then you need to declare this path in configuration.yaml

```
zha:
  custom_quirks_path: /home/homeassistant/custom_zha_quirks/
```

Restart Home Assistant, remove your device and redo the pairing.
You should see in the log that HA is using the custom quirk for the PTVO device.

You might want to enable debug log by inserting these statements in configuration.yaml

```
logger:
  default: warning
  logs:
    homeassistant.components.zha: debug
    bellows.zigbee.application: debug
    zigpy.zcl: debug
    zhaquirks: debug
    ptvo: debug
```

You should then see something like this as a confirmation that HA is actually using the new quirk:

2021-06-30 13:35:05 DEBUG (MainThread) [zhaquirks] Loading custom quirks from /home/homeassistant/custom_zha_quirks
2021-06-30 13:35:05 DEBUG (MainThread) [zhaquirks] Loading custom quirks module ptvo
